/**
 * Country information configuration
 * Provides enriched data for country detail modals
 */

import type { CountryInfo } from '$lib/types';
import { SANCTIONED_COUNTRY_IDS } from './map';
import { COUNTRY_ID_TO_NAME } from './countries';

// Reverse lookup: country name to ID
const COUNTRY_NAME_TO_ID: Record<string, number> = {};
for (const [id, name] of Object.entries(COUNTRY_ID_TO_NAME)) {
	COUNTRY_NAME_TO_ID[name] = Number(id);
}

/**
 * Country flags by name
 */
const COUNTRY_FLAGS: Record<string, string> = {
	'United States': '🇺🇸',
	'Canada': '🇨🇦',
	'Mexico': '🇲🇽',
	'United Kingdom': '🇬🇧',
	'France': '🇫🇷',
	'Germany': '🇩🇪',
	'Italy': '🇮🇹',
	'Spain': '🇪🇸',
	'Poland': '🇵🇱',
	'Ukraine': '🇺🇦',
	'Russia': '🇷🇺',
	'China': '🇨🇳',
	'Japan': '🇯🇵',
	'South Korea': '🇰🇷',
	'North Korea': '🇰🇵',
	'India': '🇮🇳',
	'Pakistan': '🇵🇰',
	'Iran': '🇮🇷',
	'Iraq': '🇮🇶',
	'Israel': '🇮🇱',
	'Saudi Arabia': '🇸🇦',
	'Turkey': '🇹🇷',
	'Egypt': '🇪🇬',
	'South Africa': '🇿🇦',
	'Nigeria': '🇳🇬',
	'Brazil': '🇧🇷',
	'Argentina': '🇦🇷',
	'Australia': '🇦🇺',
	'Taiwan': '🇹🇼',
	'Vietnam': '🇻🇳',
	'Thailand': '🇹🇭',
	'Indonesia': '🇮🇩',
	'Philippines': '🇵🇭',
	'Malaysia': '🇲🇾',
	'Singapore': '🇸🇬',
	'Venezuela': '🇻🇪',
	'Colombia': '🇨🇴',
	'Chile': '🇨🇱',
	'Peru': '🇵🇪',
	'Cuba': '🇨🇺',
	'Syria': '🇸🇾',
	'Afghanistan': '🇦🇫',
	'Yemen': '🇾🇪',
	'Libya': '🇱🇾',
	'Sudan': '🇸🇩',
	'South Sudan': '🇸🇸',
	'Ethiopia': '🇪🇹',
	'Kenya': '🇰🇪',
	'Tanzania': '🇹🇿',
	'Democratic Republic of the Congo': '🇨🇩',
	'Morocco': '🇲🇦',
	'Algeria': '🇩🇿',
	'Tunisia': '🇹🇳',
	'Greece': '🇬🇷',
	'Portugal': '🇵🇹',
	'Netherlands': '🇳🇱',
	'Belgium': '🇧🇪',
	'Sweden': '🇸🇪',
	'Norway': '🇳🇴',
	'Denmark': '🇩🇰',
	'Finland': '🇫🇮',
	'Switzerland': '🇨🇭',
	'Austria': '🇦🇹',
	'Czech Republic': '🇨🇿',
	'Hungary': '🇭🇺',
	'Romania': '🇷🇴',
	'Bulgaria': '🇧🇬',
	'Serbia': '🇷🇸',
	'Croatia': '🇭🇷',
	'Ireland': '🇮🇪',
	'New Zealand': '🇳🇿',
	'Bangladesh': '🇧🇩',
	'Myanmar': '🇲🇲',
	'Cambodia': '🇰🇭',
	'Laos': '🇱🇦',
	'Nepal': '🇳🇵',
	'Sri Lanka': '🇱🇰',
	'Kazakhstan': '🇰🇿',
	'Uzbekistan': '🇺🇿',
	'Georgia': '🇬🇪',
	'Armenia': '🇦🇲',
	'Azerbaijan': '🇦🇿',
	'Belarus': '🇧🇾',
	'Moldova': '🇲🇩',
	'Latvia': '🇱🇻',
	'Lithuania': '🇱🇹',
	'Estonia': '🇪🇪',
	'Iceland': '🇮🇸',
	'Luxembourg': '🇱🇺',
	'Malta': '🇲🇹',
	'Cyprus': '🇨🇾',
	'Slovenia': '🇸🇮',
	'Slovakia': '🇸🇰',
	'Bosnia and Herzegovina': '🇧🇦',
	'North Macedonia': '🇲🇰',
	'Albania': '🇦🇱',
	'Montenegro': '🇲🇪',
	'Kosovo': '🇽🇰',
	'Lebanon': '🇱🇧',
	'Jordan': '🇯🇴',
	'Kuwait': '🇰🇼',
	'Qatar': '🇶🇦',
	'United Arab Emirates': '🇦🇪',
	'Oman': '🇴🇲',
	'Bahrain': '🇧🇭',
	'Hong Kong': '🇭🇰',
	'Macao': '🇲🇴',
	'Mongolia': '🇲🇳'
};

/**
 * Country regions
 */
const COUNTRY_REGIONS: Record<string, string> = {
	'United States': 'North America',
	'Canada': 'North America',
	'Mexico': 'North America',
	'United Kingdom': 'Europe',
	'France': 'Europe',
	'Germany': 'Europe',
	'Italy': 'Europe',
	'Spain': 'Europe',
	'Poland': 'Europe',
	'Ukraine': 'Europe',
	'Russia': 'Europe/Asia',
	'China': 'East Asia',
	'Japan': 'East Asia',
	'South Korea': 'East Asia',
	'North Korea': 'East Asia',
	'Taiwan': 'East Asia',
	'India': 'South Asia',
	'Pakistan': 'South Asia',
	'Iran': 'Middle East',
	'Iraq': 'Middle East',
	'Israel': 'Middle East',
	'Saudi Arabia': 'Middle East',
	'Turkey': 'Middle East',
	'Egypt': 'North Africa',
	'South Africa': 'Sub-Saharan Africa',
	'Nigeria': 'Sub-Saharan Africa',
	'Brazil': 'South America',
	'Argentina': 'South America',
	'Australia': 'Oceania',
	'Vietnam': 'Southeast Asia',
	'Thailand': 'Southeast Asia',
	'Indonesia': 'Southeast Asia',
	'Philippines': 'Southeast Asia',
	'Malaysia': 'Southeast Asia',
	'Singapore': 'Southeast Asia',
	'Venezuela': 'South America',
	'Colombia': 'South America',
	'Chile': 'South America',
	'Peru': 'South America',
	'Cuba': 'Caribbean',
	'Syria': 'Middle East',
	'Afghanistan': 'Central Asia',
	'Yemen': 'Middle East',
	'Libya': 'North Africa',
	'Sudan': 'North Africa',
	'South Sudan': 'Sub-Saharan Africa',
	'Ethiopia': 'Sub-Saharan Africa',
	'Kenya': 'Sub-Saharan Africa'
};

/**
 * Country capitals
 */
const COUNTRY_CAPITALS: Record<string, string> = {
	'United States': 'Washington, D.C.',
	'Canada': 'Ottawa',
	'Mexico': 'Mexico City',
	'United Kingdom': 'London',
	'France': 'Paris',
	'Germany': 'Berlin',
	'Italy': 'Rome',
	'Spain': 'Madrid',
	'Poland': 'Warsaw',
	'Ukraine': 'Kyiv',
	'Russia': 'Moscow',
	'China': 'Beijing',
	'Japan': 'Tokyo',
	'South Korea': 'Seoul',
	'North Korea': 'Pyongyang',
	'Taiwan': 'Taipei',
	'India': 'New Delhi',
	'Pakistan': 'Islamabad',
	'Iran': 'Tehran',
	'Iraq': 'Baghdad',
	'Israel': 'Jerusalem',
	'Saudi Arabia': 'Riyadh',
	'Turkey': 'Ankara',
	'Egypt': 'Cairo',
	'South Africa': 'Pretoria',
	'Nigeria': 'Abuja',
	'Brazil': 'Brasília',
	'Argentina': 'Buenos Aires',
	'Australia': 'Canberra',
	'Vietnam': 'Hanoi',
	'Thailand': 'Bangkok',
	'Indonesia': 'Jakarta',
	'Philippines': 'Manila',
	'Malaysia': 'Kuala Lumpur',
	'Singapore': 'Singapore',
	'Venezuela': 'Caracas',
	'Colombia': 'Bogotá',
	'Chile': 'Santiago',
	'Peru': 'Lima',
	'Cuba': 'Havana',
	'Syria': 'Damascus',
	'Afghanistan': 'Kabul',
	'Yemen': "Sana'a",
	'Libya': 'Tripoli',
	'Sudan': 'Khartoum',
	'South Sudan': 'Juba',
	'Ethiopia': 'Addis Ababa',
	'Kenya': 'Nairobi'
};

/**
 * Get country info for display in modal
 */
export function getCountryInfo(countryName: string): CountryInfo {
	const countryId = COUNTRY_NAME_TO_ID[countryName];
	const isSanctioned = countryId ? SANCTIONED_COUNTRY_IDS.includes(countryId) : false;

	return {
		name: countryName,
		flag: COUNTRY_FLAGS[countryName] || '🏳️',
		region: COUNTRY_REGIONS[countryName],
		capital: COUNTRY_CAPITALS[countryName],
		isSanctioned
	};
}
